### PR TITLE
preserve original code and refactor

### PR DESCRIPTION
**Pull request by Kek5chen**
getGuildMessage is annotated Nullable

### CODE REVIEW

**Comment by RoanH** [comment]
Seems like I did not get a notification for this and hence kinda missed it until now... Either way, changes like this should probably be sent to the main JDA repository instead of this fork. For the change itself though, it is true that `getGuildMessageChannel` is nullable. However the channel will never be null here as we first check that the channel is actually from a guild, which guarantees that the `GuildMessageChannel` will be non-null.

**Comment by Kek5chen** [comment]
I have seen that, it still bothers me though to this day that it _theoretically_ is nullable. I'm more on the compilers side here.

**Comment by Kek5chen** [comment]
Also, i opened a pull request here because at the time where this was relevant, your pull request was not accepted to the main repo.

**Comment by RoanH** [comment]
Sure, but if a change like that were to be made it should probably be done everywhere instead of just in one place. Refactoring by checking against explicit channel types is also not really ideal though as future channel types without permission containers would make the original bug resurface (forum channels would most likely do this).

**Pull request closed without merging**
